baseURL = 'https://pascal-holy.github.io/blog/'
languageCode = 'de-de'
title = 'Pascal Holys Blog'
theme = 'hello-friend-ng'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Meine Reise in die Welt des Solarpunk"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "My Solarpunk Blog"
  keywords = "solarpunk, blog, berlin"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "solarpunk"
    series   = "series"

[languages]
  [languages.en]
    title = "Pascal Holy"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    

  [languages.en.params]
    subtitle  = "Blog"
    readOtherPosts = "Weitere Posts"

  [languages.en.params.logo]
    logoText = "sprich Freund und tritt ein"
    logoHomeLink = "/blog"
  [languages.de]
    title = "Pascal Holy"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    

  [languages.de.params]
    subtitle  = "Blog"
    readOtherPosts = "Weitere Posts"
    [languages.de.params.logo]
      logoText = "sprich Freund und tritt ein"
      logoHomeLink = "/blog"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
